# This file was generated by GoReleaser. DO NOT EDIT.
class Stern < Formula
  desc "⎈ Multi pod and container log tailing for Kubernetes"
  homepage "https://github.com/stern/stern"
  version "1.13.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stern/stern/releases/download/v1.13.0/stern_1.13.0_darwin_amd64.tar.gz"
    sha256 "42140383f484c18011c31c782bebb607980e34147a9859dc8d5300a17cef0479"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/stern/stern/releases/download/v1.13.0/stern_1.13.0_linux_amd64.tar.gz"
      sha256 "4c5e069c8cfa5ee97e035094190324d1109b554fbfa2f933f19a0fd1b752da1b"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stern/stern/releases/download/v1.13.0/stern_1.13.0_linux_arm64.tar.gz"
        sha256 "b5846af6de62e77f43279fc25f8ca463788de4354d2ca20dd4331df36c189650"
      else
        url "https://github.com/stern/stern/releases/download/v1.13.0/stern_1.13.0_linux_arm.tar.gz"
        sha256 "1698a9dc49495575b9122af840d4eea557e60c03f6c21f56dee6466596a2712d"
      end
    end
  end

  def install
    bin.install "stern"
  end

  test do
    system "#{bin}/stern --version"
  end
end
